unit uUnicodeTables;

interface

uses
  JvCharMap;

type
  RFilter = record
    Name: string;
    Value: TJvCharMapUnicodeFilter;
  end;

const
  FilterTable: array[TJvCharMapUnicodeFilter] of RFilter =
  (
   (Name: '(keine)';                                     Value: ufUndefined ),
   (Name: 'Basic Latin (ASCII-Codetabelle)';             Value: ufBasicLatin),
   (Name: 'Latin-1 (Codetabelle von ISO 8859-1)';        Value: ufLatin1Supplement),
   (Name: 'Latin Extended-A';                            Value: ufLatinExtendedA),
   (Name: 'Latin Extended-B';                            Value: ufLatinExtendedB),
   (Name: 'IPA Extensions';                              Value: ufIPAExtensions),
   (Name: 'Spacing Modifier Letters';                    Value: ufSpacingModifierLetters),
   (Name: 'Combining Diacritical Marks';                 Value: ufCombiningDiacriticalMarks),
   (Name: 'Greek';                                       Value: ufGreek),
   (Name: 'Cyrillic';                                    Value: ufCyrillic),
   (Name: 'Armenian';                                    Value: ufArmenian),
   (Name: 'Hebrew';                                      Value: ufHebrew),
   (Name: 'Arabic';                                      Value: ufArabic),
   (Name: 'Syriac';                                      Value: ufSyriac),
   (Name: 'Thaana';                                      Value: ufThaana),
   (Name: 'Devanagari';                                  Value: ufDevanagari),
   (Name: 'Bengali';                                     Value: ufBengali),
   (Name: 'Gurmukhi';                                    Value: ufGurmukhi),
   (Name: 'Gujarati';                                    Value: ufGujarati),
   (Name: 'Oriya';                                       Value: ufOriya),
   (Name: 'Tamil';                                       Value: ufTamil),
   (Name: 'Telugu';                                      Value: ufTelugu),
   (Name: 'Kannada';                                     Value: ufKannada),
   (Name: 'Malayalam';                                   Value: ufMalayalam),
   (Name: 'Sinhala';                                     Value: ufSinhala),
   (Name: 'Thai';                                        Value: ufThai),
   (Name: 'Lao';                                         Value: ufLao),
   (Name: 'Tibetan';                                     Value: ufTibetan),
   (Name: 'Myanmar';                                     Value: ufMyanmar),
   (Name: 'Georgian';                                    Value: ufGeorgian),
   (Name: 'Hangul Jamo';                                 Value: ufHangulJamo),
   (Name: 'Ethiopic';                                    Value: ufEthiopic),
   (Name: 'Cherokee';                                    Value: ufCherokee),
   (Name: 'Unfied Canadian Aboriginal Syllabics';        Value: ufUnifiedCanadianAboriginalSyllabics),
   (Name: 'Ogham';                                       Value: ufOgham),
   (Name: 'Runic';                                       Value: ufRunic),
   (Name: 'Khmer';                                       Value: ufKhmer),
   (Name: 'Mongolian';                                   Value: ufMongolian),
   (Name: 'Latin Extended Additional';                   Value: ufLatinExtendedAdditional),
   (Name: 'Greek Extended';                              Value: ufGreekExtended),
   (Name: 'General Punctuation';                         Value: ufGeneralPunctuation),
   (Name: 'Superscripts and Subscripts';                 Value: ufSuperscriptsAndSubscripts),
   (Name: 'Currency Symbols';                            Value: ufCurrencySymbols),
   (Name: 'Combining Diacritical Marks for Symbols';     Value: ufCombiningMarksForSymbols),
   (Name: 'Letterlike Symbols';                          Value: ufLetterlikeSymbols),
   (Name: 'Number Forms';                                Value: ufNumberForms),
   (Name: 'Arrows';                                      Value: ufArrows),
   (Name: 'Mathematical Operators';                      Value: ufMathematicalOperators),
   (Name: 'Miscellaneous Technical';                     Value: ufMiscellaneousTechnical),
   (Name: 'Control Pictures';                            Value: ufControlPictures),
   (Name: 'Optical Character Recognition';               Value: ufOpticalCharacterRecognition),
   (Name: 'Enclosed Alphanumerics';                      Value: ufEnclosedAlphanumerics),
   (Name: 'Box Drawing';                                 Value: ufBoxDrawing),
   (Name: 'Block Elements';                              Value: ufBlockElements),
   (Name: 'Geometric Shapes';                            Value: ufGeometricShapes),
   (Name: 'Miscellaneous Symbols';                       Value: ufMiscellaneousSymbols),
   (Name: 'Dingbats';                                    Value: ufDingbats),
   (Name: 'Braille Patterns';                            Value: ufBraillePatterns),
   (Name: 'CJK Radicals Supplement';                     Value: ufCJKRadicalsSupplement),
   (Name: 'Kangxi Radicals';                             Value: ufKangxiRadicals),
   (Name: 'Ideographic Description Characters';          Value: ufIdeographicDescriptionCharacters),
   (Name: 'CJK Symbols and Punctuation';                 Value: ufCJKSymbolsAndPunctuation),
   (Name: 'Hiragana';                                    Value: ufHiragana),
   (Name: 'Katakana';                                    Value: ufKatakana),
   (Name: 'Bopomofo';                                    Value: ufBopomofo),
   (Name: 'Hangul Compatibility Jamo';                   Value: ufHangulCompatibilityJamo),
   (Name: 'Kanbun';                                      Value: ufKanbun),
   (Name: 'Bopomofo Extended';                           Value: ufBopomofoExtended),
   (Name: 'Enclosed CJK Letters and Months';             Value: ufEnclosedCJKLettersAndMonths),
   (Name: 'CJK Compatibility';                           Value: ufCJKCompatibility),
   (Name: 'CJK Unified Ideographs Extension A';          Value: ufCJKUnifiedIdeographsExtensionA),
   (Name: 'CJK Unified Ideographs';                      Value: ufCJKUnifiedIdeographs),
   (Name: 'Yi Syllables';                                Value: ufYiSyllables),
   (Name: 'Yi Radicals';                                 Value: ufYiRadicals),
   (Name: 'Hangul Syllables';                            Value: ufHangulSyllables),
   (Name: 'High Surrogates';                             Value: ufHighSurrogates),
   (Name: 'Private Use High Surrogates';                 Value: ufHighPrivateUseSurrogates),
   (Name: 'Low Surrogates';                              Value: ufLowSurrogates),
   (Name: 'Private Use Area';                            Value: ufPrivateUse),
   (Name: 'CJK Compatibility Ideographs';                Value: ufCJKCompatibilityIdeographs),
   (Name: 'Alphabetic Presentation Forms';               Value: ufAlphabeticPresentationForms),
   (Name: 'Arabic Presentation Forms-A';                 Value: ufArabicPresentationFormsA),
   (Name: 'Combining Half Marks';                        Value: ufCombiningHalfMarks),
   (Name: 'CJK Compatibility Forms';                     Value: ufCJKCompatibilityForms),
   (Name: 'Small Form Variants';                         Value: ufSmallFormVariants),
   (Name: 'Arabic Presentation Forms-B';                 Value: ufArabicPresentationFormsB),
   (Name: 'Specials';                                    Value: ufSpecials),
   (Name: 'Halfwidth and Fullwidth Forms';               Value: ufHalfwidthAndFullwidthForms),
   (Name: 'Old Italic';                                  Value: ufOldItalic),
   (Name: 'Gothic';                                      Value: ufGothic),
   (Name: 'Deseret';                                     Value: ufDeseret),
   (Name: 'Byzantine Musical Symbols';                   Value: ufByzantineMusicalSymbols),
   (Name: 'Musical Symbols';                             Value: ufMusicalSymbols),
   (Name: 'Mathematical Alphanumeric Symbols';           Value: ufMathematicalAlphanumericSymbols),
   (Name: 'CJK Unified Ideographs Extension B';          Value: ufCJKUnifiedIdeographsExtensionB),
   (Name: 'CJK Compatibility Ideographs Supplement';     Value: ufCJKCompatibilityIdeographsSupplement),
   (Name: 'Tags';                                        Value: ufTags)
  );

type
  RHtmlName = record
    Zeichen: WideChar;
    HtmlName: string;
    Beschreibung: string;
  end;

const
  HtmlNameTable: array[0..251] of RHtmlName =
  (
   (Zeichen: WideChar(34);    HtmlName: '&quot;';      Beschreibung: 'Anf¸hrungszeichen oben'),
   (Zeichen: WideChar(38);    HtmlName: '&amp;';       Beschreibung: 'Ampersand-Zeichen, kaufm‰nnisches Und'),
   (Zeichen: WideChar(60);    HtmlName: '&lt;';        Beschreibung: 'ˆffnende spitze Klammer'),
   (Zeichen: WideChar(62);    HtmlName: '&gt;';        Beschreibung: 'schlieﬂende spitze Klammer'),
   (Zeichen: WideChar(160);   HtmlName: '&nbsp;';      Beschreibung: 'Erzwungenes Leerzeichen'),
   (Zeichen: WideChar(161);   HtmlName: '&iexcl;';     Beschreibung: 'umgekehrtes Ausrufezeichen'),
   (Zeichen: WideChar(162);   HtmlName: '&cent;';      Beschreibung: 'Cent-Zeichen'),
   (Zeichen: WideChar(163);   HtmlName: '&pound;';     Beschreibung: 'Pfund-Zeichen'),
   (Zeichen: WideChar(164);   HtmlName: '&curren;';    Beschreibung: 'W‰hrungszeichen'),
   (Zeichen: WideChar(165);   HtmlName: '&yen;';       Beschreibung: 'Yen-Zeichen'),
   (Zeichen: WideChar(166);   HtmlName: '&brvbar;';    Beschreibung: 'durchbrochener Strich'),
   (Zeichen: WideChar(167);   HtmlName: '&sect;';      Beschreibung: 'Paragraph-Zeichen'),
   (Zeichen: WideChar(168);   HtmlName: '&uml;';       Beschreibung: 'P¸nktchen oben'),
   (Zeichen: WideChar(169);   HtmlName: '&copy;';      Beschreibung: 'Copyright-Zeichen'),
   (Zeichen: WideChar(170);   HtmlName: '&ordf;';      Beschreibung: 'Ordinal-Zeichen weiblich'),
   (Zeichen: WideChar(171);   HtmlName: '&laquo;';     Beschreibung: 'angewinkelte Anf¸hrungszeichen links'),
   (Zeichen: WideChar(172);   HtmlName: '&not;';       Beschreibung: 'Verneinungs-Zeichen'),
   (Zeichen: WideChar(173);   HtmlName: '&shy;';       Beschreibung: 'bedingter Trennstrich'),
   (Zeichen: WideChar(174);   HtmlName: '&reg;';       Beschreibung: 'Registriermarke-Zeichen'),
   (Zeichen: WideChar(175);   HtmlName: '&macr;';      Beschreibung: '‹berstrich'),
   (Zeichen: WideChar(176);   HtmlName: '&deg;';       Beschreibung: 'Grad-Zeichen'),
   (Zeichen: WideChar(177);   HtmlName: '&plusmn;';    Beschreibung: 'Plusminus-Zeichen'),
   (Zeichen: WideChar(178);   HtmlName: '&sup2;';      Beschreibung: 'Hoch-2-Zeichen'),
   (Zeichen: WideChar(179);   HtmlName: '&sup3;';      Beschreibung: 'Hoch-3-Zeichen'),
   (Zeichen: WideChar(180);   HtmlName: '&acute;';     Beschreibung: 'Akut-Zeichen'),
   (Zeichen: WideChar(181);   HtmlName: '&micro;';     Beschreibung: 'Mikro-Zeichen'),
   (Zeichen: WideChar(182);   HtmlName: '&para;';      Beschreibung: 'Absatz-Zeichen'),
   (Zeichen: WideChar(183);   HtmlName: '&middot;';    Beschreibung: 'Mittelpunkt'),
   (Zeichen: WideChar(184);   HtmlName: '&cedil;';     Beschreibung: 'H‰kchen unten'),
   (Zeichen: WideChar(185);   HtmlName: '&sup1;';      Beschreibung: 'Hoch-1-Zeichen'),
   (Zeichen: WideChar(186);   HtmlName: '&ordm;';      Beschreibung: 'Ordinal-Zeichen m‰nnlich'),
   (Zeichen: WideChar(187);   HtmlName: '&raquo;';     Beschreibung: 'angewinkelte Anf¸hrungszeichen rechts'),
   (Zeichen: WideChar(188);   HtmlName: '&frac14;';    Beschreibung: 'ein Viertel'),
   (Zeichen: WideChar(189);   HtmlName: '&frac12;';    Beschreibung: 'ein Halb'),
   (Zeichen: WideChar(190);   HtmlName: '&frac34;';    Beschreibung: 'drei Viertel'),
   (Zeichen: WideChar(191);   HtmlName: '&iquest;';    Beschreibung: 'umgekehrtes Fragezeichen'),
   (Zeichen: WideChar(192);   HtmlName: '&Agrave;';    Beschreibung: 'A mit accent grave (Gravis)'),
   (Zeichen: WideChar(193);   HtmlName: '&Aacute;';    Beschreibung: 'A mit accent aigu (Akut)'),
   (Zeichen: WideChar(194);   HtmlName: '&Acirc;';     Beschreibung: 'A mit Zirkumflex'),
   (Zeichen: WideChar(195);   HtmlName: '&Atilde;';    Beschreibung: 'A mit Tilde'),
   (Zeichen: WideChar(196);   HtmlName: '&Auml;';      Beschreibung: 'A Umlaut'),
   (Zeichen: WideChar(197);   HtmlName: '&Aring;';     Beschreibung: 'A mit Ring'),
   (Zeichen: WideChar(198);   HtmlName: '&AElig;';     Beschreibung: 'A mit legiertem E'),
   (Zeichen: WideChar(199);   HtmlName: '&Ccedil;';    Beschreibung: 'C mit H‰kchen'),
   (Zeichen: WideChar(200);   HtmlName: '&Egrave;';    Beschreibung: 'E mit accent grave (Gravis)'),
   (Zeichen: WideChar(201);   HtmlName: '&Eacute;';    Beschreibung: 'E mit accent aigu (Akut)'),
   (Zeichen: WideChar(202);   HtmlName: '&Ecirc;';     Beschreibung: 'E mit Zirkumflex'),
   (Zeichen: WideChar(203);   HtmlName: '&Euml;';      Beschreibung: 'E Umlaut'),
   (Zeichen: WideChar(204);   HtmlName: '&Igrave;';    Beschreibung: 'I mit accent grave (Gravis)'),
   (Zeichen: WideChar(205);   HtmlName: '&Iacute;';    Beschreibung: 'I mit accent aigu (Akut)'),
   (Zeichen: WideChar(206);   HtmlName: '&Icirc;';     Beschreibung: 'I mit Zirkumflex'),
   (Zeichen: WideChar(207);   HtmlName: '&Iuml;';      Beschreibung: 'I Umlaut'),
   (Zeichen: WideChar(208);   HtmlName: '&ETH;';       Beschreibung: 'groﬂes Eth (isl‰ndisch)'),
   (Zeichen: WideChar(209);   HtmlName: '&Ntilde;';    Beschreibung: 'N mit Tilde'),
   (Zeichen: WideChar(210);   HtmlName: '&Ograve;';    Beschreibung: 'O mit accent grave (Gravis)'),
   (Zeichen: WideChar(211);   HtmlName: '&Oacute;';    Beschreibung: 'O mit accent aigu (Akut)'),
   (Zeichen: WideChar(212);   HtmlName: '&Ocirc;';     Beschreibung: 'O mit Zirkumflex'),
   (Zeichen: WideChar(213);   HtmlName: '&Otilde;';    Beschreibung: 'O mit Tilde'),
   (Zeichen: WideChar(214);   HtmlName: '&Ouml;';      Beschreibung: 'O Umlaut'),
   (Zeichen: WideChar(215);   HtmlName: '&times;';     Beschreibung: 'Mal-Zeichen'),
   (Zeichen: WideChar(216);   HtmlName: '&Oslash;';    Beschreibung: 'O mit Schr‰gstrich'),
   (Zeichen: WideChar(217);   HtmlName: '&Ugrave;';    Beschreibung: 'U mit accent grave (Gravis)'),
   (Zeichen: WideChar(218);   HtmlName: '&Uacute;';    Beschreibung: 'U mit accent aigu (Akut)'),
   (Zeichen: WideChar(219);   HtmlName: '&Ucirc;';     Beschreibung: 'U mit Zirkumflex'),
   (Zeichen: WideChar(220);   HtmlName: '&Uuml;';      Beschreibung: 'U Umlaut'),
   (Zeichen: WideChar(221);   HtmlName: '&Yacute;';    Beschreibung: 'Y mit accent aigu (Akut)'),
   (Zeichen: WideChar(222);   HtmlName: '&THORN;';     Beschreibung: 'groﬂes Thorn (isl‰ndisch)'),
   (Zeichen: WideChar(223);   HtmlName: '&szlig;';     Beschreibung: 'scharfes S'),
   (Zeichen: WideChar(224);   HtmlName: '&agrave;';    Beschreibung: 'a mit accent grave (Gravis)'),
   (Zeichen: WideChar(225);   HtmlName: '&aacute;';    Beschreibung: 'a mit accent aigu (Akut)'),
   (Zeichen: WideChar(226);   HtmlName: '&acirc;';     Beschreibung: 'a mit Zirkumflex'),
   (Zeichen: WideChar(227);   HtmlName: '&atilde;';    Beschreibung: 'a mit Tilde'),
   (Zeichen: WideChar(228);   HtmlName: '&auml;';      Beschreibung: 'a Umlaut'),
   (Zeichen: WideChar(229);   HtmlName: '&aring;';     Beschreibung: 'a mit Ring'),
   (Zeichen: WideChar(230);   HtmlName: '&aelig;';     Beschreibung: 'a mit legiertem e'),
   (Zeichen: WideChar(231);   HtmlName: '&ccedil;';    Beschreibung: 'c mit H‰kchen'),
   (Zeichen: WideChar(232);   HtmlName: '&egrave;';    Beschreibung: 'e mit accent grave (Gravis)'),
   (Zeichen: WideChar(233);   HtmlName: '&eacute;';    Beschreibung: 'e mit accent aigu (Akut)'),
   (Zeichen: WideChar(234);   HtmlName: '&ecirc;';     Beschreibung: 'e mit Zirkumflex'),
   (Zeichen: WideChar(235);   HtmlName: '&euml;';      Beschreibung: 'e Umlaut'),
   (Zeichen: WideChar(236);   HtmlName: '&igrave;';    Beschreibung: 'i mit accent grave (Gravis)'),
   (Zeichen: WideChar(237);   HtmlName: '&iacute;';    Beschreibung: 'i mit accent aigu (Akut)'),
   (Zeichen: WideChar(238);   HtmlName: '&icirc;';     Beschreibung: 'i mit Zirkumflex'),
   (Zeichen: WideChar(239);   HtmlName: '&iuml;';      Beschreibung: 'i Umlaut'),
   (Zeichen: WideChar(240);   HtmlName: '&eth;';       Beschreibung: 'kleines Eth (isl‰ndisch)'),
   (Zeichen: WideChar(241);   HtmlName: '&ntilde;';    Beschreibung: 'n mit Tilde'),
   (Zeichen: WideChar(242);   HtmlName: '&ograve;';    Beschreibung: 'o mit accent grave (Gravis)'),
   (Zeichen: WideChar(243);   HtmlName: '&oacute;';    Beschreibung: 'o mit accent aigu (Akut)'),
   (Zeichen: WideChar(244);   HtmlName: '&ocirc;';     Beschreibung: 'o mit Zirkumflex'),
   (Zeichen: WideChar(245);   HtmlName: '&otilde;';    Beschreibung: 'o mit Tilde'),
   (Zeichen: WideChar(246);   HtmlName: '&ouml;';      Beschreibung: 'o Umlaut'),
   (Zeichen: WideChar(247);   HtmlName: '&divide;';    Beschreibung: 'Divisions-Zeichen'),
   (Zeichen: WideChar(248);   HtmlName: '&oslash;';    Beschreibung: 'o mit Schr‰gstrich'),
   (Zeichen: WideChar(249);   HtmlName: '&ugrave;';    Beschreibung: 'u mit accent grave (Gravis)'),
   (Zeichen: WideChar(250);   HtmlName: '&uacute;';    Beschreibung: 'u mit accent aigu (Akut)'),
   (Zeichen: WideChar(251);   HtmlName: '&ucirc;';     Beschreibung: 'u mit Zirkumflex'),
   (Zeichen: WideChar(252);   HtmlName: '&uuml;';      Beschreibung: 'u Umlaut'),
   (Zeichen: WideChar(253);   HtmlName: '&yacute;';    Beschreibung: 'y mit accent aigu (Akut)'),
   (Zeichen: WideChar(254);   HtmlName: '&thorn;';     Beschreibung: 'kleines Thorn (isl‰ndisch)'),
   (Zeichen: WideChar(255);   HtmlName: '&yuml;';      Beschreibung: 'y Umlaut'),
   (Zeichen: WideChar(913);   HtmlName: '&Alpha;';     Beschreibung: 'Alpha groﬂ'),
   (Zeichen: WideChar(945);   HtmlName: '&alpha;';     Beschreibung: 'alpha klein'),
   (Zeichen: WideChar(914);   HtmlName: '&Beta;';      Beschreibung: 'Beta groﬂ'),
   (Zeichen: WideChar(946);   HtmlName: '&beta;';      Beschreibung: 'beta klein'),
   (Zeichen: WideChar(915);   HtmlName: '&Gamma;';     Beschreibung: 'Gamma groﬂ'),
   (Zeichen: WideChar(947);   HtmlName: '&gamma;';     Beschreibung: 'gamma klein'),
   (Zeichen: WideChar(916);   HtmlName: '&Delta;';     Beschreibung: 'Delta groﬂ'),
   (Zeichen: WideChar(948);   HtmlName: '&delta;';     Beschreibung: 'delta klein'),
   (Zeichen: WideChar(917);   HtmlName: '&Epsilon;';   Beschreibung: 'Epsilon groﬂ'),
   (Zeichen: WideChar(949);   HtmlName: '&epsilon;';   Beschreibung: 'epsilon klein'),
   (Zeichen: WideChar(918);   HtmlName: '&Zeta;';      Beschreibung: 'Zeta groﬂ'),
   (Zeichen: WideChar(950);   HtmlName: '&zeta;';      Beschreibung: 'zeta klein'),
   (Zeichen: WideChar(919);   HtmlName: '&Eta;';       Beschreibung: 'Eta groﬂ'),
   (Zeichen: WideChar(951);   HtmlName: '&eta;';       Beschreibung: 'eta klein'),
   (Zeichen: WideChar(920);   HtmlName: '&Theta;';     Beschreibung: 'Theta groﬂ'),
   (Zeichen: WideChar(952);   HtmlName: '&theta;';     Beschreibung: 'theta klein'),
   (Zeichen: WideChar(921);   HtmlName: '&Iota;';      Beschreibung: 'Iota groﬂ'),
   (Zeichen: WideChar(953);   HtmlName: '&iota;';      Beschreibung: 'iota klein'),
   (Zeichen: WideChar(922);   HtmlName: '&Kappa;';     Beschreibung: 'Kappa groﬂ'),
   (Zeichen: WideChar(954);   HtmlName: '&kappa;';     Beschreibung: 'kappa klein'),
   (Zeichen: WideChar(923);   HtmlName: '&Lambda;';    Beschreibung: 'Lambda groﬂ'),
   (Zeichen: WideChar(955);   HtmlName: '&lambda;';    Beschreibung: 'lambda klein'),
   (Zeichen: WideChar(924);   HtmlName: '&Mu;';        Beschreibung: 'My groﬂ'),
   (Zeichen: WideChar(956);   HtmlName: '&mu;';        Beschreibung: 'my klein'),
   (Zeichen: WideChar(925);   HtmlName: '&Nu;';        Beschreibung: 'Ny groﬂ'),
   (Zeichen: WideChar(957);   HtmlName: '&nu;';        Beschreibung: 'ny klein'),
   (Zeichen: WideChar(926);   HtmlName: '&Xi;';        Beschreibung: 'Xi groﬂ'),
   (Zeichen: WideChar(958);   HtmlName: '&xi;';        Beschreibung: 'xi klein'),
   (Zeichen: WideChar(927);   HtmlName: '&Omicron;';   Beschreibung: 'Omikron groﬂ'),
   (Zeichen: WideChar(959);   HtmlName: '&omicron;';   Beschreibung: 'omikron klein'),
   (Zeichen: WideChar(928);   HtmlName: '&Pi;';        Beschreibung: 'Pi groﬂ'),
   (Zeichen: WideChar(960);   HtmlName: '&pi;';        Beschreibung: 'pi klein'),
   (Zeichen: WideChar(929);   HtmlName: '&Rho;';       Beschreibung: 'Rho groﬂ'),
   (Zeichen: WideChar(961);   HtmlName: '&rho;';       Beschreibung: 'rho klein'),
   (Zeichen: WideChar(931);   HtmlName: '&Sigma;';     Beschreibung: 'Sigma groﬂ'),
   (Zeichen: WideChar(962);   HtmlName: '&sigmaf;';    Beschreibung: 'Schluss-Sigma'),
   (Zeichen: WideChar(963);   HtmlName: '&sigma;';     Beschreibung: 'sigma klein'),
   (Zeichen: WideChar(932);   HtmlName: '&Tau;';       Beschreibung: 'Tau groﬂ'),
   (Zeichen: WideChar(964);   HtmlName: '&tau;';       Beschreibung: 'tau klein'),
   (Zeichen: WideChar(933);   HtmlName: '&Upsilon;';   Beschreibung: 'Ypsilon groﬂ'),
   (Zeichen: WideChar(965);   HtmlName: '&upsilon;';   Beschreibung: 'ypsilon klein'),
   (Zeichen: WideChar(934);   HtmlName: '&Phi;';       Beschreibung: 'Phi groﬂ'),
   (Zeichen: WideChar(966);   HtmlName: '&phi;';       Beschreibung: 'phi klein'),
   (Zeichen: WideChar(935);   HtmlName: '&Chi;';       Beschreibung: 'Chi groﬂ'),
   (Zeichen: WideChar(967);   HtmlName: '&chi;';       Beschreibung: 'chi klein'),
   (Zeichen: WideChar(936);   HtmlName: '&Psi;';       Beschreibung: 'Psi groﬂ'),
   (Zeichen: WideChar(968);   HtmlName: '&psi;';       Beschreibung: 'psi klein'),
   (Zeichen: WideChar(937);   HtmlName: '&Omega;';     Beschreibung: 'Omega groﬂ'),
   (Zeichen: WideChar(969);   HtmlName: '&omega;';     Beschreibung: 'omega klein'),
   (Zeichen: WideChar(977);   HtmlName: '&thetasym;';  Beschreibung: 'theta Symbol'),
   (Zeichen: WideChar(978);   HtmlName: '&upsih;';     Beschreibung: 'ypsilon mit Haken'),
   (Zeichen: WideChar(982);   HtmlName: '&piv;';       Beschreibung: 'pi Symbol'),
   (Zeichen: WideChar(8704);  HtmlName: '&forall;';    Beschreibung: 'f¸r alle'),
   (Zeichen: WideChar(8706);  HtmlName: '&part;';      Beschreibung: 'partiell'),
   (Zeichen: WideChar(8707);  HtmlName: '&exist;';     Beschreibung: 'existiert'),
   (Zeichen: WideChar(8709);  HtmlName: '&empty;';     Beschreibung: 'leere Menge'),
   (Zeichen: WideChar(8711);  HtmlName: '&nabla;';     Beschreibung: 'Nabla'),
   (Zeichen: WideChar(8712);  HtmlName: '&isin;';      Beschreibung: 'Element von'),
   (Zeichen: WideChar(8713);  HtmlName: '&notin;';     Beschreibung: 'kein Element von'),
   (Zeichen: WideChar(8715);  HtmlName: '&ni;';        Beschreibung: 'Element von (gespiegelt)'),
   (Zeichen: WideChar(8719);  HtmlName: '&prod;';      Beschreibung: 'Produkt'),
   (Zeichen: WideChar(8721);  HtmlName: '&sum;';       Beschreibung: 'Summe'),
   (Zeichen: WideChar(8722);  HtmlName: '&minus;';     Beschreibung: 'minus'),
   (Zeichen: WideChar(8727);  HtmlName: '&lowast;';    Beschreibung: 'Asterisk'),
   (Zeichen: WideChar(8730);  HtmlName: '&radic;';     Beschreibung: 'Wurzel'),
   (Zeichen: WideChar(8733);  HtmlName: '&prop;';      Beschreibung: 'proportional zu'),
   (Zeichen: WideChar(8734);  HtmlName: '&infin;';     Beschreibung: 'unendlich'),
   (Zeichen: WideChar(8736);  HtmlName: '&ang;';       Beschreibung: 'Winkel'),
   (Zeichen: WideChar(8743);  HtmlName: '&and;';       Beschreibung: 'und'),
   (Zeichen: WideChar(8744);  HtmlName: '&or;';        Beschreibung: 'oder'),
   (Zeichen: WideChar(8745);  HtmlName: '&cap;';       Beschreibung: 'Schnittmenge'),
   (Zeichen: WideChar(8746);  HtmlName: '&cup;';       Beschreibung: 'Vereinigungsmenge'),
   (Zeichen: WideChar(8747);  HtmlName: '&int;';       Beschreibung: 'Integral'),
   (Zeichen: WideChar(8756);  HtmlName: '&there4;';    Beschreibung: 'deshalb'),
   (Zeichen: WideChar(8764);  HtmlName: '&sim;';       Beschreibung: '‰hnlich wie'),
   (Zeichen: WideChar(8773);  HtmlName: '&cong;';      Beschreibung: 'kongruent'),
   (Zeichen: WideChar(8776);  HtmlName: '&asymp;';     Beschreibung: 'beinahe gleich'),
   (Zeichen: WideChar(8800);  HtmlName: '&ne;';        Beschreibung: 'ungleich'),
   (Zeichen: WideChar(8801);  HtmlName: '&equiv;';     Beschreibung: 'identisch mit'),
   (Zeichen: WideChar(8804);  HtmlName: '&le;';        Beschreibung: 'kleiner gleich'),
   (Zeichen: WideChar(8805);  HtmlName: '&ge;';        Beschreibung: 'grˆﬂer gleich'),
   (Zeichen: WideChar(8834);  HtmlName: '&sub;';       Beschreibung: 'Untermenge von'),
   (Zeichen: WideChar(8835);  HtmlName: '&sup;';       Beschreibung: 'Obermenge von'),
   (Zeichen: WideChar(8836);  HtmlName: '&nsub;';      Beschreibung: 'keine Untermenge von'),
   (Zeichen: WideChar(8838);  HtmlName: '&sube;';      Beschreibung: 'Untermenge von oder gleich mit'),
   (Zeichen: WideChar(8839);  HtmlName: '&supe;';      Beschreibung: 'Obermenge von oder gleich mit'),
   (Zeichen: WideChar(8853);  HtmlName: '&oplus;';     Beschreibung: 'Restklassenaddition'),
   (Zeichen: WideChar(8855);  HtmlName: '&otimes;';    Beschreibung: 'Kronecker-Produkt'),
   (Zeichen: WideChar(8869);  HtmlName: '&perp;';      Beschreibung: 'senkrecht zu'),
   (Zeichen: WideChar(8901);  HtmlName: '&sdot;';      Beschreibung: 'Punkt-Operator'),
   (Zeichen: WideChar(9674);  HtmlName: '&loz;';       Beschreibung: 'Raute'),
   (Zeichen: WideChar(8968);  HtmlName: '&lceil;';     Beschreibung: 'links oben'),
   (Zeichen: WideChar(8969);  HtmlName: '&rceil;';     Beschreibung: 'rechts oben'),
   (Zeichen: WideChar(8970);  HtmlName: '&lfloor;';    Beschreibung: 'links unten'),
   (Zeichen: WideChar(8971);  HtmlName: '&rfloor;';    Beschreibung: 'rechts unten'),
   (Zeichen: WideChar(9001);  HtmlName: '&lang;';      Beschreibung: 'spitze Klammer links'),
   (Zeichen: WideChar(9002);  HtmlName: '&rang;';      Beschreibung: 'spitze Klammer rechts'),
   (Zeichen: WideChar(8592);  HtmlName: '&larr;';      Beschreibung: 'Pfeil links'),
   (Zeichen: WideChar(8593);  HtmlName: '&uarr;';      Beschreibung: 'Pfeil oben'),
   (Zeichen: WideChar(8594);  HtmlName: '&rarr;';      Beschreibung: 'Pfeil rechts'),
   (Zeichen: WideChar(8595);  HtmlName: '&darr;';      Beschreibung: 'Pfeil unten'),
   (Zeichen: WideChar(8596);  HtmlName: '&harr;';      Beschreibung: 'Pfeil links/rechts'),
   (Zeichen: WideChar(8629);  HtmlName: '&crarr;';     Beschreibung: 'Pfeil unten-Knick-links'),
   (Zeichen: WideChar(8656);  HtmlName: '&lArr;';      Beschreibung: 'Doppelpfeil links'),
   (Zeichen: WideChar(8657);  HtmlName: '&uArr;';      Beschreibung: 'Doppelpfeil oben'),
   (Zeichen: WideChar(8658);  HtmlName: '&rArr;';      Beschreibung: 'Doppelpfeil rechts'),
   (Zeichen: WideChar(8659);  HtmlName: '&dArr;';      Beschreibung: 'Doppelpfeil unten'),
   (Zeichen: WideChar(8660);  HtmlName: '&hArr;';      Beschreibung: 'Doppelpfeil links/rechts'),
   (Zeichen: WideChar(8226);  HtmlName: '&bull;';      Beschreibung: 'Bullet-Zeichen'),
   (Zeichen: WideChar(8242);  HtmlName: '&prime;';     Beschreibung: 'Minutenzeichen'),
   (Zeichen: WideChar(8243);  HtmlName: '&Prime;';     Beschreibung: 'Sekundenzeichen'),
   (Zeichen: WideChar(8254);  HtmlName: '&oline;';     Beschreibung: '‹berstrich'),
   (Zeichen: WideChar(8260);  HtmlName: '&frasl;';     Beschreibung: 'Bruchstrich'),
   (Zeichen: WideChar(8472);  HtmlName: '&weierp;';    Beschreibung: 'Weierstraﬂ p'),
   (Zeichen: WideChar(8465);  HtmlName: '&image;';     Beschreibung: 'Zeichen f¸r "imagin‰r"'),
   (Zeichen: WideChar(8476);  HtmlName: '&real;';      Beschreibung: 'Zeichen f¸r "real"'),
   (Zeichen: WideChar(8482);  HtmlName: '&trade;';     Beschreibung: 'Trademark-Zeichen'),
   (Zeichen: WideChar(8364);  HtmlName: '&euro;';      Beschreibung: 'Euro-Zeichen'),
   (Zeichen: WideChar(8501);  HtmlName: '&alefsym;';   Beschreibung: 'Alef-Symbol'),
   (Zeichen: WideChar(9824);  HtmlName: '&spades;';    Beschreibung: 'Pik-Zeichen'),
   (Zeichen: WideChar(9827);  HtmlName: '&clubs;';     Beschreibung: 'Kreuz-Zeichen'),
   (Zeichen: WideChar(9829);  HtmlName: '&hearts;';    Beschreibung: 'Herz-Zeichen'),
   (Zeichen: WideChar(9830);  HtmlName: '&diams;';     Beschreibung: 'Karo-Zeichen'),
   (Zeichen: WideChar(338);   HtmlName: '&OElig;';     Beschreibung: 'OE-Ligatur'),
   (Zeichen: WideChar(339);   HtmlName: '&oelig;';     Beschreibung: 'oe-Ligatur'),
   (Zeichen: WideChar(352);   HtmlName: '&Scaron;';    Beschreibung: 'S mit Zirkumflex'),
   (Zeichen: WideChar(353);   HtmlName: '&scaron;';    Beschreibung: 's mit Zirkumflex'),
   (Zeichen: WideChar(376);   HtmlName: '&Yuml;';      Beschreibung: 'Y Umlaut'),
   (Zeichen: WideChar(402);   HtmlName: '&fnof;';      Beschreibung: 'Funktion'),
   (Zeichen: WideChar(8194);  HtmlName: '&ensp;';      Beschreibung: 'Leerzeichen Breite n'),
   (Zeichen: WideChar(8195);  HtmlName: '&emsp;';      Beschreibung: 'Leerzeichen Breite m'),
   (Zeichen: WideChar(8201);  HtmlName: '&thinsp;';    Beschreibung: 'Schmales Leerzeichen'),
   (Zeichen: WideChar(8204);  HtmlName: '&zwnj;';      Beschreibung: 'null breiter Nichtverbinder'),
   (Zeichen: WideChar(8205);  HtmlName: '&zwj;';       Beschreibung: 'null breiter Verbinder'),
   (Zeichen: WideChar(8206);  HtmlName: '&lrm;';       Beschreibung: 'links-nach-rechts-Zeichen'),
   (Zeichen: WideChar(8207);  HtmlName: '&rlm;';       Beschreibung: 'rechts-nach-links-Zeichen'),
   (Zeichen: WideChar(8211);  HtmlName: '&ndash;';     Beschreibung: 'Gedankenstrich Breite n'),
   (Zeichen: WideChar(8212);  HtmlName: '&mdash;';     Beschreibung: 'Gedankenstrich Breite m'),
   (Zeichen: WideChar(8216);  HtmlName: '&lsquo;';     Beschreibung: 'einfaches Anf¸hrungszeichen links'),
   (Zeichen: WideChar(8217);  HtmlName: '&rsquo;';     Beschreibung: 'einfaches Anf¸hrungszeichen rechts'),
   (Zeichen: WideChar(8218);  HtmlName: '&sbquo;';     Beschreibung: 'einfaches low-9-Zeichen'),
   (Zeichen: WideChar(8220);  HtmlName: '&ldquo;';     Beschreibung: 'doppeltes Anf¸hrungszeichen links'),
   (Zeichen: WideChar(8221);  HtmlName: '&rdquo;';     Beschreibung: 'doppeltes Anf¸hrungszeichen rechts'),
   (Zeichen: WideChar(8222);  HtmlName: '&bdquo;';     Beschreibung: 'doppeltes low-9-Zeichen rechts'),
   (Zeichen: WideChar(8224);  HtmlName: '&dagger;';    Beschreibung: 'Kreuz'),
   (Zeichen: WideChar(8225);  HtmlName: '&Dagger;';    Beschreibung: 'Doppelkreuz'),
   (Zeichen: WideChar(8230);  HtmlName: '&hellip;';    Beschreibung: 'Horizontale Ellipse (Auslassungszeichen)'),
   (Zeichen: WideChar(8240);  HtmlName: '&permil;';    Beschreibung: 'Promille'),
   (Zeichen: WideChar(8249);  HtmlName: '&lsaquo;';    Beschreibung: 'angewinkeltes einzelnes Anf.zeichen links'),
   (Zeichen: WideChar(8250);  HtmlName: '&rsaquo;';    Beschreibung: 'angewinkeltes einzelnes Anf.zeichen rechts'),
   (Zeichen: WideChar(710);   HtmlName: '&circ;';      Beschreibung: 'Zirkumflex'),
   (Zeichen: WideChar(732);   HtmlName: '&tilde;';     Beschreibung: 'kleine Tilde')
  );

implementation

end.
